runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

#- url: /(.*)
#  static_files: www/\1
#  upload: www/(.*)

- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)

- url: /data/(.*)
  static_files: data/\1
  upload: data/(.*)

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
